### PR TITLE
tests: remove useless test files

### PR DESCRIPTION
**Pull request by imeoer**
## Relevant Issue (if applicable)
_If there are Issues related to this PullRequest, please list it._

## Details
_Please describe the details of PullRequest._

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by bergwolf** [comment]
The code coverage is down by `-1.97%`. Does it mean that we haven't covered all the cases that are tested by either the python test or the rust smoke test?

**Comment by adamqqqplay** [comment]
> The code coverage is down by `-1.97%`. Does it mean that we haven't covered all the cases that are tested by either the python test or the rust smoke test?

Currently, we only count unit test coverage in this project.

**Comment by imeoer** [comment]
@bergwolf This may be due to the codecov CI tests failing for a period of time. (The repository name has been changed to nydus.) —— from @adamqqqplay

**Review by adam3q — APPROVED** [review]
LGTM

**Review by Desiki-high — APPROVED** [review]
LGTM!

**Pull request merged**
