### PR TITLE
nydusify: upgrade containerd package

### PR DESCRIPTION
**Pull request by imeoer**
To import some fixups from https://github.com/containerd/containerd/pull/9405.

## Relevant Issue (if applicable)
_If there are Issues related to this PullRequest, please list it._

## Details
_Please describe the details of PullRequest._

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Desiki-high** [comment]
Why not base on the latest version of `containerd`, such as https://github.com/containerd/containerd/tree/release/1.7.

**Comment by imeoer** [comment]
> Why not base on the latest version of `containerd`, such as https://github.com/containerd/containerd/tree/release/1.7.

We depend on the unmerged PR https://github.com/containerd/containerd/pull/9405

**Comment by Desiki-high** [comment]
> > Why not base on the latest version of `containerd`, such as https://github.com/containerd/containerd/tree/release/1.7.
> 
> We depend on the unmerged PR [containerd/containerd#9405](https://github.com/containerd/containerd/pull/9405)

So what is different between https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked and https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked-v1, you want to rebase to https://github.com/nydusaccelerator/containerd/commit/4f03e100cb967922bec7459a78d16ccbac9bb81d?

**Comment by Desiki-high** [comment]
> > > Why not base on the latest version of `containerd`, such as https://github.com/containerd/containerd/tree/release/1.7.
> > 
> > 
> > We depend on the unmerged PR [containerd/containerd#9405](https://github.com/containerd/containerd/pull/9405)
> 
> So what is different between https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked and https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked-v1, you want to rebase to [containerd/containerd@4f03e10](https://github.com/containerd/containerd/commit/4f03e100cb967922bec7459a78d16ccbac9bb81d)?

I notice https://github.com/containerd/containerd/pull/9405 is from [nydusaccelerator:remotes-push-in-chunked](https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked)

**Comment by imeoer** [comment]
> I notice [containerd/containerd#9405](https://github.com/containerd/containerd/pull/9405) is from [nydusaccelerator:remotes-push-in-chunked](https://github.com/nydusaccelerator/containerd/tree/remotes-push-in-chunked).

Thanks for the careful review, the `remotes-push-in-chunked-v1` branch is based on containerd `v1.7` but `remotes-push-in-chunked` is based on containerd v2.0 (i.e., the latest `upstream/main` of containerd), for now nydusify can only be based on the containerd v1 package.

**Review by Desiki-high — APPROVED** [review]
LGTM

**Pull request merged**
