### PR TITLE
docs: add pull request and issue templates

### PR DESCRIPTION
**Pull request by adam3q**
## Relevant Issue (if applicable)
#1285

## Details
Provide pull requests and issue templates to standardize project contribution standards.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Desiki-high** [comment]
@adamqqqplay Maybe add a section: Screenshots (if applicable)? Sometimes pictures are more intuitive than words.

**Comment by adamqqqplay** [comment]
> @adamqqqplay Maybe add a section: Screenshots (if applicable)? Sometimes pictures are more intuitive than words.

Looks good.

**Review by Desiki-high — APPROVED** [review]

**Comment by Desiki-high** [comment]
@adamqqqplay We can add more issue templates for different kinds of issues. Such as ```github/ISSUE_TEMPLATE/bug_report.md```, ```.github/ISSUE_TEMPLATE/feture_request.md ```, ```.github/ISSUE_TEMPLATE/other.md```. Otherwise everything all in one template. Thanks.

**Comment by adamqqqplay** [comment]
> @adamqqqplay We can add more issue templates for different kinds of issues. Such as `.github/ISSUE_TEMPLATE/bug_report.md`, `.github/ISSUE_TEMPLATE/feture_request.md `, `.github/ISSUE_TEMPLATE/other.md`. Otherwise everything all in one template. Thanks.

@Desiki-high We can see the effect first, and I will submit an update in another PR later.

**Pull request merged**
