### PR TITLE
docs: fix docker-env-setup.md

### PR DESCRIPTION
**Pull request by peng-yq**
## Relevant Issue (if applicable)

#1633
 
## Details

Just fix the manual.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by imeoer — APPROVED** [review]
LGTM, thanks!

**Comment by imeoer** [comment]
@peng-yq Let's pass the DCO check with `git commit -s`. :)

**Review by peng-yq — COMMENTED** [review]
@imeoer Already done! Sorry for my lack of skill : (.

**Review by imeoer — APPROVED** [review]
Thanks!

**Comment by imeoer** [comment]
@peng-yq Please also submit a PR to master branch, thanks!

**Comment by peng-yq** [comment]
> @peng-yq Please also submit a PR to master branch, thanks!

Sure! I'll check the manual of the master branch.

**Comment by peng-yq** [comment]
@imeoer , Already submit a PR to the master branch #1645.

**Pull request merged**
