### PR TITLE
chore: remove go test cover

### PR DESCRIPTION
**Pull request by Desiki-high**
## Relevant Issue (if applicable)
image

## Details
In golang smoke test, go test don't need coverage analysis and create coverage profile.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by adam3q — COMMENTED** [review]
@Desiki-high Does this step affect execution time?

**Comment by Desiki-high** [comment]
> > @Desiki-high Does this step affect execution time?
> 
> I'm not sure about the execution time. I need to test it.

In my local machine or Github Action, this step doesn't affect execution time. In my point, the `-cover` testflag doesn't make any sense.

**Comment by adamqqqplay** [comment]
> > > @Desiki-high Does this step affect execution time?
> > 
> > 
> > I'm not sure about the execution time. I need to test it.
> 
> In my local machine or Github Action, this step doesn't affect execution time. In my point, the `-cover` testflag doesn't make any sense.

@Desiki-high Ok, I see. In addition, if you have time, can you help add the coverage statistics of nydusify and other go modules to codecov? Thanks in advance.

**Review by adam3q — APPROVED** [review]

**Comment by Desiki-high** [comment]
> > > > @Desiki-high Does this step affect execution time?
> > > 
> > > 
> > > I'm not sure about the execution time. I need to test it.
> > 
> > 
> > In my local machine or Github Action, this step doesn't affect execution time. In my point, the `-cover` testflag doesn't make any sense.
> 
> @Desiki-high Ok, I see. In addition, if you have time, can you help add the coverage statistics of nydusify and other go modules to codecov? Thanks in advance.

I can have a try.

**Comment by adamqqqplay** [comment]
> > > > > @Desiki-high Does this step affect execution time?
> > > > 
> > > > 
> > > > I'm not sure about the execution time. I need to test it.
> > > 
> > > 
> > > In my local machine or Github Action, this step doesn't affect execution time. In my point, the `-cover` testflag doesn't make any sense.
> > 
> > 
> > @Desiki-high Ok, I see. In addition, if you have time, can you help add the coverage statistics of nydusify and other go modules to codecov? Thanks in advance.
> 
> I can have a try.

Thanks for your help. I will submit an new issue to track this.

**Comment by Desiki-high** [comment]
> > > > > > @Desiki-high Does this step affect execution time?
> > > > > 
> > > > > 
> > > > > I'm not sure about the execution time. I need to test it.
> > > > 
> > > > 
> > > > In my local machine or Github Action, this step doesn't affect execution time. In my point, the `-cover` testflag doesn't make any sense.
> > > 
> > > 
> > > @Desiki-high Ok, I see. In addition, if you have time, can you help add the coverage statistics of nydusify and other go modules to codecov? Thanks in advance.
> > 
> > 
> > I can have a try.
> 
> Thanks for your help. I will submit an new issue to track this.


I have create at #1517.

**Pull request merged**
