### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jiangliu**
Update dependency

### CODE REVIEW

**Comment by yqleng1987** [comment]
@jiangliu , the title has been updated, so a new test job has been submitted. Please wait in patience. The test job url: [https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267](https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267)

**Comment by yqleng1987** [comment]
@jiangliu , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-ctr-remote</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus-snapshotter</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">start-nydus-snapshotter-config-containerd</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">run-container-with-nydus-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15267>:x: FAIL</a></td>
    </tr>
</table>

Sorry, your test job failed. Please get the details in the link.

**Comment by yqleng1987** [comment]
@jiangliu , the code has been updated, so a new test job has been submitted. Please wait in patience. The test job url: [https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276](https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276)

**Comment by yqleng1987** [comment]
@jiangliu , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-ctr-remote</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus-snapshotter</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">start-nydus-snapshotter-config-containerd</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">run-container-with-nydus-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/15276>:white_check_mark: SUCCESS</a></td>
    </tr>
</table>

Congratulations, your test job passed!

**Review by imeoer — APPROVED** [review]

**Pull request merged**
