### PR TITLE
action: test build with more architectures

### PR DESCRIPTION
**Pull request by Desiki-high**
## Relevant Issue (if applicable)
https://github.com/dragonflyoss/nydus/actions/workflows/release.yml?query=event%3Aschedule

## Details
To prevent build errors in different architectures, we should test build with more architectures in `Smoke Test`, but only use `amd64` in the next jobs.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Desiki-high** [comment]
It looks like [`dbs-snapshot`](https://github.com/kata-containers/dbs-snapshot/blob/main/src/lib.rs#L40-L44) don't support `riscv64` and `ppc64le`, So the [`Release`](https://github.com/dragonflyoss/nydus/actions/workflows/release.yml?query=event%3Aschedule) failed.

**Comment by imeoer** [comment]
Thanks for the PR, it seems we need to make `dbs-snapshot` also work on `ppc64le` and `riscv64`: https://github.com/kata-containers/dbs-snapshot/blob/098fca6c819fc3e3be4329e1cf8b09f98450b3be/src/lib.rs#L41, are you interested in submitting a PR for `dbs-snapshot`? It's a rust crate we maintained.

**Comment by Desiki-high** [comment]
> Thanks for the PR, it seems we need to make `dbs-snapshot` also work on `ppc64le` and `riscv64`: https://github.com/kata-containers/dbs-snapshot/blob/098fca6c819fc3e3be4329e1cf8b09f98450b3be/src/lib.rs#L41, are you interested in submitting a PR for `dbs-snapshot`? It's a rust crate we maintained.

I can try it later.

**Comment by Desiki-high** [comment]
Try to fix it at https://github.com/kata-containers/dbs-snapshot/pull/5.

**Review by imeoer — APPROVED** [review]
LGTM

**Pull request merged**
