### PR TITLE
tests: add go module unit coverage statistics in Codecov

### LINKED ISSUE #1518: Need add go module unit coverage statistics in Codecov
Currently, only rust code is included in codecov's test coverage statistics. We should also count the coverage of go modules such as nydusify, so that we can better understand the overall test coverage of the nydus project.

Steps that may be needed:
1. Enhance makefiles such as nydusify.
2. Add a new step in .github/workflows/smoke.yml to get go module coverage.
3. Modify .github/codecov.yml.

Reference: https://github.com/dragonflyoss/nydus/pull/1228

### PR DESCRIPTION
**Pull request by Desiki-high**
## Relevant Issue (if applicable)
resolve https://github.com/dragonflyoss/nydus/issues/1518.

## Details
1. Add `contrib-unit-test-coverage` job to test the Golang modules in contrib.
2. Upload both rust and golang coverage files to Codecov.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Desiki-high** [comment]
It seems Codecov can't processes the [report file](https://api.codecov.io/upload/gh/dragonflyoss/nydus/download?path=v4/raw/2023-12-18/FF63B18FC59CE7F8D35CA546FCD2DD04/7bd960a9ecae0065f9ff708de32d8f4dabc1da75/60900678-85e2-422d-a4ac-0191dbb7ee49.txt), see https://app.codecov.io/github/dragonflyoss/nydus/commit/7bd960a9ecae0065f9ff708de32d8f4dabc1da75.

**Comment by Desiki-high** [comment]
@adamqqqplay Can you help me take a look at the `Codecov`, I'm not very familiar with this. It looks like we need this : 
image
But in my report file it looks like this:
image

**Comment by Desiki-high** [comment]
I forgot to check out the git repo, all fixed. Ref: https://docs.codecov.com/docs/fixing-paths.

**Comment by Desiki-high** [comment]
The coverage has decreased due to the addition of new go modules.

**Review by imeoer — APPROVED** [review]
LGTM!

**Comment by adamqqqplay** [comment]
@Desiki-high Thank you for your great work, really helpful.

**Pull request merged**
