### PR TITLE
tests: remove useless test files

### PR DESCRIPTION
**Pull request by Desiki-high**
## Relevant Issue (if applicable)
N/A

## Details
Since https://github.com/dragonflyoss/nydus/pull/983, we have the new smoke test, we can remove the old smoke test files of nydusify and nydus.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by imeoer — APPROVED** [review]
LGTM, thanks!

**Comment by adamqqqplay** [comment]
@Desiki-high @imeoer I'm not very confident about this PR. Are we sure all nydusify tests have been migrated to smoke tests?

**Comment by Desiki-high** [comment]
> confident 

Most of the tests are covered by smoke, and I will add the tests to `nydusify/pkg` in the future for the parts that are not covered.

**Comment by Desiki-high** [comment]
@adamqqqplay If you find that certain tests are not be covered, feel free to point them out for me. Thanks.

**Comment by adamqqqplay** [comment]
@Desiki-high Thanks for the explanation, I'll let you know if I find any problems.

**Pull request merged**
