### PR TITLE
upgrade clap to 3.2.12

### PR DESCRIPTION
**Pull request by uran0sH**
In order to use derive API to refactor, we upgrade clap firstly.

issue: https://github.com/dragonflyoss/image-service/issues/296

### CODE REVIEW

**Comment by yqleng1987** [comment]
@uran0sH , a new test job has been submitted. Please wait in patience. The test job url: [https://tone.openanolis.cn/ws/nrh4nnio/test_result/13425](https://tone.openanolis.cn/ws/nrh4nnio/test_result/13425)

**Comment by yqleng1987** [comment]
@uran0sH , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13426>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13426>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13426>:x: FAIL</a></td>
    </tr>
</table>

Sorry, your test job failed. Please get the details in the link.

**Comment by liubogithub** [comment]
Any problem if we use the  derive api in the same PR?

**Comment by yqleng1987** [comment]
@uran0sH , the code has been updated, so a new test job has been submitted. Please wait in patience. The test job url: [https://tone.openanolis.cn/ws/nrh4nnio/test_result/13461](https://tone.openanolis.cn/ws/nrh4nnio/test_result/13461)

**Comment by yqleng1987** [comment]
@uran0sH , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13461>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13461>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/13461>:x: FAIL</a></td>
    </tr>
</table>

Sorry, your test job failed. Please get the details in the link.

**Comment by yqleng1987** [comment]
@uran0sH , the code has been updated, so a new test job has been submitted. Please wait in patience. The test job url: [https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023](https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023)

**Comment by uran0sH** [comment]
> Any problem if we use the derive api in the same PR?

It should be quite a lot of work to use the derive api instead. Should it be better to split it into two PRs?

**Comment by yqleng1987** [comment]
@uran0sH , The CI test is completed, please check result:
<table>
    <tr>
        <th colspan="2">Test Case</th><th>Test Result</th>
    </tr>
    <tr>
        <td colspan="2">merge-target-branch</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">build-docker-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-ctr-remote</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">compile-nydus-snapshotter</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">start-nydus-snapshotter-config-containerd</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
    <tr>
        <td colspan="2">run-container-with-nydus-image</td><td><a href=https://tone.openanolis.cn/ws/nrh4nnio/test_result/14023>:white_check_mark: SUCCESS</a></td>
    </tr>
</table>

Congratulations, your test job passed!

**Comment by liubogithub** [comment]
> > Any problem if we use the derive api in the same PR?
> 
> It should be quite a lot of work to use the derive api instead. Should it be better to split it into two PRs?

Hmm, I don't think it really benefits us by a single version upgrade of clap, can you please mark it as a WIP and fill in with upcoming commits of derive api?

**Comment by uran0sH** [comment]
> > > Any problem if we use the derive api in the same PR?
> > 
> > 
> > It should be quite a lot of work to use the derive api instead. Should it be better to split it into two PRs?
> 
> Hmm, I don't think it really benefits us by a single version upgrade of clap, can you please mark it as a WIP and fill in with upcoming commits of derive api?

Yeah, of course.

**Comment by yqleng1987** [comment]
@uran0sH , the title of this PR starts with "WIP" or "[WIP]", so skip testing for now.

**Comment by imeoer** [comment]
@uran0sH Have any updates for this?

**Comment by uran0sH** [comment]
See a new pr: #822

**Comment by uran0sH** [comment]
See a new pr: https://github.com/dragonflyoss/image-service/pull/822

**Pull request closed without merging**
