### PR TITLE
feat: support more images for benchmark

### PR DESCRIPTION
**Pull request by Desiki-high**
### 2.  support more images in benchamrk.
| image | status |workflow|stable version test|                                                                                                                                 
| :----:|:------:|:-------|:-------------:|
| wordpress |✅|wait the 80 port response|[6.1.1](https://github.com/dragonflyoss/image-service/actions/runs/4905410815#summary-13290406408)|
|node|✅ |node misc/benchmark/node/index.js & wait the 80 port response|[19.8](https://github.com/dragonflyoss/image-service/actions/runs/4905270374#summary-13290108714)|
|python|✅ |python -c 'print(\"hello\")'|[3.10.7](https://github.com/dragonflyoss/image-service/actions/runs/4905347730#summary-13290238833)|
|golang|✅ |go run misc/benchmark/go/main.go|[1.19.3](https://github.com/dragonflyoss/image-service/actions/runs/4905380439#summary-13290308178)|
|ruby|✅ |ruby -e "puts \\"hello\\""|[3.1.3](https://github.com/dragonflyoss/image-service/actions/runs/4905403314#summary-13290357533)|
|java(amazoncorretto)|✅ |javac msic/becnhmark/java/Main.java & java Main|[8-al2022-jdk](https://github.com/dragonflyoss/image-service/actions/runs/4905408629#summary-13290380744)|

### CODE REVIEW

**Comment by Desiki-high** [comment]
Next Wokr: test these images on schedule.

**Comment by imeoer** [comment]
Hi @Desiki-high, any example to preview the results of these images?

**Comment by Desiki-high** [comment]
> Hi @Desiki-high, any example to preview the results of these images?

See the link in stable version test.

**Comment by Desiki-high** [comment]
> > Hi @Desiki-high, any example to preview the results of these images?
> 
> See the link in stable version test.

You can see the image changes of workflows file in smoke.

**Comment by Desiki-high** [comment]
@imeoer Is there any problems else about this PR?

**Review by imeoer — APPROVED** [review]

**Pull request merged**
