### PR TITLE
rust: bump 1.72.1 and fix errors

### PR DESCRIPTION
**Pull request by Desiki-high**
## Relevant Issue (if applicable)
N/A.

## Details
Bump rust 1.72.1 and fix errors and warnings.
ref:
https://rust-lang.github.io/rust-clippy/master/index.html#non_minimal_cfg
https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
https://rust-lang.github.io/rust-clippy/master/index.html#reserve_after_initializatio
https://rust-lang.github.io/rust-clippy/master/index.html#/arc_with_non_send_sync
https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by imeoer** [comment]
Thanks for the work, how about using the latest rust stable `1.75.0` ?

**Comment by Desiki-high** [comment]
> Thanks for the work, how about using the latest rust stable `1.75.0` ?

I just found out that the latest version is 1.74.1: https://github.com/rust-lang/rust/releases/tag/1.74.1 .

**Comment by imeoer** [comment]
> I just found out that the latest version is 1.74.1: https://github.com/rust-lang/rust/releases/tag/1.74.1 .

Ok, strange page [here](https://releases.rs/).

**Comment by Desiki-high** [comment]
> > I just found out that the latest version is 1.74.1: https://github.com/rust-lang/rust/releases/tag/1.74.1 .
> 
> Ok, strange page [here](https://releases.rs/).

It looks like a release roadmap, maybe v1.75 will be released later. Anyway, I think v1.74.1 can be accepted.

**Comment by adamqqqplay** [comment]
@Desiki-high I recommend upgrading the rust version to 1.72.0 (or 1.72.1). 
This version is currently used by the [Kata Containers](https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L375). If the nydus version is too high, it may introduce some dependency problems.

**Comment by Desiki-high** [comment]
> @Desiki-high I recommend upgrading the rust version to 1.72.0 (or 1.72.1). This version is currently used by the [Kata Containers](https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L375). If the nydus version is too high, it may introduce some dependency problems.

Thanks for your reminder.

**Review by imeoer — APPROVED** [review]
Great work, thanks!

**Comment by adamqqqplay** [comment]
Thanks!

**Pull request merged**
