### PR TITLE
action: update test branch for integration

### PR DESCRIPTION
**Pull request by imeoer**
```
We are focusing on v2.2 maintenance, let's we change the test branch
from `stable/v2.1` to `stable/v2.2`.

It also fix the broken integration test:
https://github.com/dragonflyoss/image-service/actions/runs/6153232407
```

## Relevant Issue (if applicable)
_If there are Issues related to this PullRequest, please list it._

## Details
_Please describe the details of PullRequest._

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by Desiki-high — APPROVED** [review]
LGTM

**Comment by adamqqqplay** [comment]
@imeoer Maybe we could release a new version on the stable/v2.1 branch?

**Comment by imeoer** [comment]
> @imeoer Maybe we could release a new version on the stable/v2.1 branch?

We are focusing on v2.2 maintenance, do we still need to release a new `v2.1.x` ?

**Comment by adamqqqplay** [comment]
> > @imeoer Maybe we could release a new version on the stable/v2.1 branch?
> 
> We are focusing on v2.2 maintenance, do we still need to release a new `v2.1.x` ?

@imeoer It seems that there are some new changes added to the stable/v2.1 branch since v2.1.6, and it may be necessary to release a final version for them.

**Comment by imeoer** [comment]
@adamqqqplay Ok, we can do that.

**Pull request merged**
