### PR TITLE
update nydusify.md and add GO111MODULE flags for nydusify build

### PR DESCRIPTION
**Pull request by ydcool**
Signed-off-by: Dominic Yin <yindongchao@inspur.com>

### CODE REVIEW

**Comment by imeoer** [comment]
LGTM, I will put a PR to fix [these clippy errors](https://travis-ci.org/github/dragonflyoss/image-service/builds/752722041) in rust 1.49.0. :)

**Review by imeoer — APPROVED** [review]
LGTM

**Comment by bergwolf** [comment]
Thanks a lot! Please rebase to pick up the just merged travis fix.

**Pull request merged**
