### PR TITLE
storage: refine the way to implement BlobIoChunk

### PR DESCRIPTION
**Pull request by jiangliu**
Backport the new implementation of BlobIoChunk from master.

Fixes: https://github.com/dragonflyoss/image-service/issues/1198

### CODE REVIEW

**Comment by ccx1024cc** [comment]
#1198 is fixed by this PR, thx~

**Comment by ccx1024cc** [comment]
Please also backport to stable/2.2, if necessary

**Review by imeoer — APPROVED** [review]

**Comment by imeoer** [comment]
@ccx1024cc Can we test the PR for https://github.com/dragonflyoss/image-service/issues/1198 again?

**Review by ccx1024cc — CHANGES_REQUESTED** [review]
Should we remove the useless param `_device` here?

**Review by ccx1024cc — APPROVED** [review]

**Pull request merged**
