### PR TITLE
nydusify: fix overlayfs mount options for check

### PR DESCRIPTION
**Pull request by imeoer**
To fix the error when mount OCI v1 image in check subcommand:

```
error: mount options is too long
```

The mount options has 4k buffer size limitation, we will
encounter the issue in a huge image with mass layers.

We need to shorten the length of lowerdir paths in overlayfs
option, change `sha256:xxx` to `layer-N` to alleviate the issue.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>

### CODE REVIEW

**Comment by hsiangkao** [comment]
You could also use new mount api called fsopen to mount, which doesn't have 4k limitation.

**Comment by imeoer** [comment]
> You could also use new mount api called fsopen to mount, which doesn't have 4k limitation.

It looks great! we used the mount method from containerd package, maybe we can improve that for it.

**Comment by adamqqqplay** [comment]
@imeoer Will this change cause compatibility issues? Or is this just an internal change in nydusify.

**Comment by imeoer** [comment]
@adamqqqplay No, it's an internal change for `nydusify check` subcommand.

**Review by adam3q — APPROVED** [review]
LGTM

**Review by jiangliu — APPROVED** [review]

**Pull request merged**
