### PR TITLE
nydus-image: refactor subcommand "inspect"

### PR DESCRIPTION
**Pull request by YushuoEdge**
The code for "nydus-image inspect" are refactored using standard API
in RAFS.

Signed-off-by: YushuoEdge <y-shuo@sjtu.edu.cn>

### CODE REVIEW

**Comment by liubogithub** [comment]
@changweige can you please take a look?

**Comment by changweige** [comment]
> @changweige can you please take a look?

Sure. will take a glance

**Comment by YushuoEdge** [comment]
> changweige

Sorry for that. I did not find the problem when I did test before. Maybe something went wrong when I rebase to master branch, please allow me to check again and revise.

**Comment by changweige** [comment]
Please rebase your PR to get `cargo deny` passed

**Comment by YushuoEdge** [comment]
> Please rebase your PR to get `cargo deny` passed

**Review by bergwolf — COMMENTED** [review]
Nice cleanup! Thanks! Is it possible to add some test cases in smoke? There are pre-built bootstrap files under `tests/texture/bootstrap/` which can be used to test `inspect` as well.

**Comment by imeoer** [comment]
Updates: @YushuoEdge is working on smoke testing and fixing. :)

**Comment by YushuoEdge** [comment]
update:
The request_mode output of cmd `stats`, `prefetch`, `blobs ` are used in smoke test.
More tests result can refer to: https://docs.google.com/document/d/115r90YmZmRPKxEz6WEfGHD6F6eylv4lQDe-7xd_pTUI/edit?usp=sharing

**Comment by imeoer** [comment]
> update: The `request_mode` output of cmd `stats`, `prefetch`, `blobs ` are used in smoke test. More tests result can refer to: https://docs.google.com/document/d/115r90YmZmRPKxEz6WEfGHD6F6eylv4lQDe-7xd_pTUI/edit?usp=sharing

Thanks for adding the test case in smoke testing, it is difficult for us to cover all the tests of `inspect` command, a few basic checks are enough, what do you think? cc @changweige @bergwolf

**Review by bergwolf — APPROVED** [review]
Thanks a lot!

**Pull request merged**
