### PR TITLE
did you mean 'compatible'?

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by jiangliu** [comment]
Thanks for the MR, could you please help to add signoff and a better description?

**Comment by bergwolf** [comment]
@0xflotus Thanks for spotting that! Besides @jiangliu's comments, please also fix the commit title. `did you mean 'compatible'` is not a proper commit title. Something like `readme: fix typo` is much better.

**Comment by bergwolf** [comment]
Since the PR is not formatted properly and has been stale for a long time, I've raised #12 and folded the fix there. Thanks @0xflotus !

**Comment by 0xflotus** [comment]
Oh sorry, I didn't recognized it. 😓

**Pull request closed without merging**
