### PR TITLE
doc: add macos doc

### PR DESCRIPTION
**Pull request by killagu**
Signed-off-by: killagu <killa123@126.com>

### CODE REVIEW

**Comment by jiangliu** [comment]
Could you please to add some commit message to describe the change?

**Comment by killagu** [comment]
Sure. Simple message has been added to commit.

**Comment by imeoer** [comment]
Thanks! we can add a link in the home page's README.md to refer to this doc.

**Comment by killagu** [comment]
@imeoer Good idea. Now we can see nydus with macos in readme.md.

**Review by imeoer — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
